# Generated by Django 2.2 on 2021-02-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='College',
        ),
    ]
