# Generated by Django 2.2 on 2021-02-14 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0002_delete_college'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewCollegeBasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('country_id', models.CharField(blank=True, max_length=200, null=True)),
                ('state_id', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('university_id', models.CharField(blank=True, max_length=200, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('accredited_by', models.CharField(blank=True, max_length=200, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('campuz_size', models.CharField(blank=True, max_length=200, null=True)),
                ('established_on', models.CharField(blank=True, max_length=200, null=True)),
                ('genders_accepted', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.CharField(blank=True, max_length=1000, null=True)),
                ('ownership', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=10, null=True)),
                ('type', models.CharField(blank=True, max_length=200, null=True)),
                ('course_types', models.CharField(blank=True, max_length=200, null=True)),
                ('degrees', models.CharField(blank=True, max_length=200, null=True)),
                ('colg_type', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.CharField(blank=True, max_length=200, null=True)),
                ('created_time', models.CharField(blank=True, max_length=200, null=True)),
                ('affiliation', models.CharField(blank=True, max_length=200, null=True)),
                ('banner', models.TextField(blank=True, null=True)),
                ('facilities', models.CharField(blank=True, max_length=200, null=True)),
                ('modification_time', models.CharField(blank=True, max_length=200, null=True)),
                ('placement', models.CharField(blank=True, max_length=200, null=True)),
                ('placement_average', models.CharField(blank=True, max_length=200, null=True)),
                ('placement_high', models.CharField(blank=True, max_length=200, null=True)),
                ('short_desc', models.TextField(blank=True, null=True)),
                ('scholarship_providing_college', models.CharField(max_length=10)),
                ('college_website', models.CharField(max_length=200)),
                ('banner_alt_text', models.CharField(max_length=200)),
                ('logo_alt_text', models.CharField(max_length=200)),
                ('college_name_slug', models.CharField(max_length=200)),
                ('top_courses', models.CharField(max_length=200)),
                ('placement_description', models.TextField()),
                ('keywords', models.CharField(max_length=200)),
                ('verified_by_college_partner', models.CharField(max_length=45)),
                ('college_partner_id', models.CharField(max_length=200)),
                ('commission', models.CharField(max_length=200)),
                ('approved_by_admin', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'new_college_basic_info',
                'managed': False,
            },
        ),
    ]
